use adapted check-release.yaml from r-lib/actions

diff --git a/.github/workflows/test-buildlibrary.yaml b/.github/workflows/test-buildlibrary.yaml
--- a/.github/workflows/test-buildlibrary.yaml
+++ b/.github/workflows/test-buildlibrary.yaml
@@ -1,18 +1,19 @@
+# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
+# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
 on:
   push:
-    branches:
-      - main
-      - master
+    branches: [main, master]
   pull_request:
-    branches:
-      - main
-      - master
+    branches: [main, master]
 
-name: check
+name: R-CMD-check
 
 jobs:
-  check:
-    runs-on: ubuntu-20.04
+  R-CMD-check:
+    runs-on: ubuntu-latest
+    env:
+      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
+      R_KEEP_PKG_SOURCE: yes
     steps:
       - uses: actions/checkout@v2
 
@@ -31,18 +32,34 @@ jobs:
       - uses: r-lib/actions/setup-r-dependencies@v1
         with:
           extra-packages: |
-            devtools
-            covr
             lucode2
+            rcmdcheck
+            covr
 
-      - name: Run tests
-        run: devtools::test(stop_on_failure = TRUE)
+      - name: Validation key
+        run: if(!lucode2:::validkey()$valid) stop("Invalid build key!")
         shell: Rscript {0}
+
+      - name: Check
+        env:
+          _R_CHECK_CRAN_INCOMING_: false
+        run: |
+          options(crayon.enabled = TRUE)
+          rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")
+        shell: Rscript {0}
+
+      - name: Show testthat output
+        if: always()
+        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
+        shell: bash
+
+      - name: Upload check results
+        if: failure()
+        uses: actions/upload-artifact@main
+        with:
+          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
+          path: check
 
       - name: Test coverage
         run: covr::codecov(quiet = FALSE)
-        shell: Rscript {0}
-
-      - name: Validation key 
-        run: if(!lucode2:::validkey()$valid) stop("Invalid build key!")
         shell: Rscript {0}
